---
epochs: 60
batch_size: 32
net_divisor: 1
learning_rate: 0.001
num_workers: 12
img_dir_train: ./data/places16/train
img_dir_val: ./data/places16/val
img_dir_test: ./data/places16/test
img_out_dir: ./out/places16
models_dir: ./model/places16